[workspace]
resolver = "2"
members = [
    "scraps/*",
    "core/*",
]

[workspace.package]
authors = ["Andreas.Zwander <Andreas.Zwander@outlook.com>"]
edition = "2024"
license = "MPL-2.0 OR GPL-3.0-or-later"
version = "0.1.0"

[workspace.dependencies]
command = {path = "core/command"}
flatpak = {path = "core/flatpak"}